### ISSUE TITLE
Length restrictions

### ISSUE THREAD

**Issue by trycontrolmymind** [coopersystem-fsd/typeorm-custom-naming-strategy#4]
I think current restrictions is too small.

For example, FK that i have:
```
> "FK_apply_template_banner_format".length
31
```

I think default max length should be more, than 30 symbols.
Is it really okay to substring name of the indices?

**Comment by bc05** [comment]
I'm sorry for the late reply bro.

In our scenario, it was necessary to limit the maximum number of characters because postgres have a limit of 30. However, in the class constructor, it is possible to pass the maximum required size as a parameter. By default, we using length 30.

**Comment by trycontrolmymind** [comment]
Oh, ok got it, strange postgres restrictions
Found additional parameter.
